application: hacktehfuture
version: 5
runtime: python
api_version: 1

default_expiration: "1d"

handlers:
  - url: /wiki
    script: wiki.py

  - url: /favicon.ico
    static_files: static/images/favicon.ico
    upload: static/images/favicon.ico

  - url: /static/images/fileicons/.*
    script: zip_handler.py

  - url: /fckeditor/.*
    script: zip_handler.py

  - url: /static
    static_dir: static

  - url: /admin/.*
    script: main.py
    login: required

  - url: /
    static_files: static_pretty/index.html
    upload: static_pretty/index.html

  - url: /
    static_dir: static_pretty

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 )$
